# render.yaml
version: 1
services:
  - type: web
    name: tiktok-video-api
    env: python
    region: oregon
    plan: free # As requested

    buildCommand: |
      echo "--- Updating apt-get and installing FFmpeg ---"
      apt-get update -y
      apt-get install -y ffmpeg
      echo "--- Installing Python dependencies ---"
      pip install -r requirements.txt

    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT

    healthCheckPath: /

    envVars:
      - key: PORT
        value: 10000 
      # --- IMPORTANT: CHANGE PYTHON VERSION HERE ---
      - key: PYTHON_VERSION
        value: 3.11.9 # Recommended: Change to 3.11.x (e.g., 3.11.9 or 3.11.8)
        # OR
        # value: 3.12.3 # If you prefer 3.12.x, but 3.11 is generally very stable